import '../localization/app_strings.dart';

class CountryOption {
  const CountryOption({required this.code});

  final String code;

  String get name =>
      AppStrings.english['country_name_${code.toLowerCase()}'] ?? code;

  String get flag => countryFlagEmoji(code);
}

String countryFlagEmoji(String? rawCode) {
  final code = (rawCode ?? '').trim().toUpperCase();
  if (!RegExp(r'^[A-Z]{2}$').hasMatch(code)) return '';
  const regionalIndicatorA = 0x1F1E6;
  const asciiA = 0x41;
  return String.fromCharCodes(<int>[
    regionalIndicatorA + code.codeUnitAt(0) - asciiA,
    regionalIndicatorA + code.codeUnitAt(1) - asciiA,
  ]);
}

CountryOption? countryOptionForCode(String? rawCode) {
  final code = (rawCode ?? '').trim().toUpperCase();
  for (final country in countryOptions) {
    if (country.code == code) return country;
  }
  return null;
}

const List<CountryOption> countryOptions = <CountryOption>[
  CountryOption(code: 'AF'),
  CountryOption(code: 'AL'),
  CountryOption(code: 'DZ'),
  CountryOption(code: 'AS'),
  CountryOption(code: 'AD'),
  CountryOption(code: 'AO'),
  CountryOption(code: 'AI'),
  CountryOption(code: 'AQ'),
  CountryOption(code: 'AG'),
  CountryOption(code: 'AR'),
  CountryOption(code: 'AM'),
  CountryOption(code: 'AW'),
  CountryOption(code: 'AU'),
  CountryOption(code: 'AT'),
  CountryOption(code: 'AZ'),
  CountryOption(code: 'BS'),
  CountryOption(code: 'BH'),
  CountryOption(code: 'BD'),
  CountryOption(code: 'BB'),
  CountryOption(code: 'BY'),
  CountryOption(code: 'BE'),
  CountryOption(code: 'BZ'),
  CountryOption(code: 'BJ'),
  CountryOption(code: 'BM'),
  CountryOption(code: 'BT'),
  CountryOption(code: 'BO'),
  CountryOption(code: 'BQ'),
  CountryOption(code: 'BA'),
  CountryOption(code: 'BW'),
  CountryOption(code: 'BV'),
  CountryOption(code: 'BR'),
  CountryOption(code: 'IO'),
  CountryOption(code: 'BN'),
  CountryOption(code: 'BG'),
  CountryOption(code: 'BF'),
  CountryOption(code: 'BI'),
  CountryOption(code: 'CV'),
  CountryOption(code: 'KH'),
  CountryOption(code: 'CM'),
  CountryOption(code: 'CA'),
  CountryOption(code: 'KY'),
  CountryOption(code: 'CF'),
  CountryOption(code: 'TD'),
  CountryOption(code: 'CL'),
  CountryOption(code: 'CN'),
  CountryOption(code: 'CX'),
  CountryOption(code: 'CC'),
  CountryOption(code: 'CO'),
  CountryOption(code: 'KM'),
  CountryOption(code: 'CG'),
  CountryOption(code: 'CD'),
  CountryOption(code: 'CK'),
  CountryOption(code: 'CR'),
  CountryOption(code: 'HR'),
  CountryOption(code: 'CU'),
  CountryOption(code: 'CW'),
  CountryOption(code: 'CY'),
  CountryOption(code: 'CZ'),
  CountryOption(code: 'CI'),
  CountryOption(code: 'DK'),
  CountryOption(code: 'DJ'),
  CountryOption(code: 'DM'),
  CountryOption(code: 'DO'),
  CountryOption(code: 'EC'),
  CountryOption(code: 'EG'),
  CountryOption(code: 'SV'),
  CountryOption(code: 'GQ'),
  CountryOption(code: 'ER'),
  CountryOption(code: 'EE'),
  CountryOption(code: 'SZ'),
  CountryOption(code: 'ET'),
  CountryOption(code: 'FK'),
  CountryOption(code: 'FO'),
  CountryOption(code: 'FJ'),
  CountryOption(code: 'FI'),
  CountryOption(code: 'FR'),
  CountryOption(code: 'GF'),
  CountryOption(code: 'PF'),
  CountryOption(code: 'TF'),
  CountryOption(code: 'GA'),
  CountryOption(code: 'GM'),
  CountryOption(code: 'GE'),
  CountryOption(code: 'DE'),
  CountryOption(code: 'GH'),
  CountryOption(code: 'GI'),
  CountryOption(code: 'GR'),
  CountryOption(code: 'GL'),
  CountryOption(code: 'GD'),
  CountryOption(code: 'GP'),
  CountryOption(code: 'GU'),
  CountryOption(code: 'GT'),
  CountryOption(code: 'GG'),
  CountryOption(code: 'GN'),
  CountryOption(code: 'GW'),
  CountryOption(code: 'GY'),
  CountryOption(code: 'HT'),
  CountryOption(code: 'HM'),
  CountryOption(code: 'VA'),
  CountryOption(code: 'HN'),
  CountryOption(code: 'HK'),
  CountryOption(code: 'HU'),
  CountryOption(code: 'IS'),
  CountryOption(code: 'IN'),
  CountryOption(code: 'ID'),
  CountryOption(code: 'IR'),
  CountryOption(code: 'IQ'),
  CountryOption(code: 'IE'),
  CountryOption(code: 'IM'),
  CountryOption(code: 'IL'),
  CountryOption(code: 'IT'),
  CountryOption(code: 'JM'),
  CountryOption(code: 'JP'),
  CountryOption(code: 'JE'),
  CountryOption(code: 'JO'),
  CountryOption(code: 'KZ'),
  CountryOption(code: 'KE'),
  CountryOption(code: 'KI'),
  CountryOption(code: 'KP'),
  CountryOption(code: 'KR'),
  CountryOption(code: 'KW'),
  CountryOption(code: 'KG'),
  CountryOption(code: 'LA'),
  CountryOption(code: 'LV'),
  CountryOption(code: 'LB'),
  CountryOption(code: 'LS'),
  CountryOption(code: 'LR'),
  CountryOption(code: 'LY'),
  CountryOption(code: 'LI'),
  CountryOption(code: 'LT'),
  CountryOption(code: 'LU'),
  CountryOption(code: 'MO'),
  CountryOption(code: 'MG'),
  CountryOption(code: 'MW'),
  CountryOption(code: 'MY'),
  CountryOption(code: 'MV'),
  CountryOption(code: 'ML'),
  CountryOption(code: 'MT'),
  CountryOption(code: 'MH'),
  CountryOption(code: 'MQ'),
  CountryOption(code: 'MR'),
  CountryOption(code: 'MU'),
  CountryOption(code: 'YT'),
  CountryOption(code: 'MX'),
  CountryOption(code: 'FM'),
  CountryOption(code: 'MD'),
  CountryOption(code: 'MC'),
  CountryOption(code: 'MN'),
  CountryOption(code: 'ME'),
  CountryOption(code: 'MS'),
  CountryOption(code: 'MA'),
  CountryOption(code: 'MZ'),
  CountryOption(code: 'MM'),
  CountryOption(code: 'NA'),
  CountryOption(code: 'NR'),
  CountryOption(code: 'NP'),
  CountryOption(code: 'NL'),
  CountryOption(code: 'NC'),
  CountryOption(code: 'NZ'),
  CountryOption(code: 'NI'),
  CountryOption(code: 'NE'),
  CountryOption(code: 'NG'),
  CountryOption(code: 'NU'),
  CountryOption(code: 'NF'),
  CountryOption(code: 'MK'),
  CountryOption(code: 'MP'),
  CountryOption(code: 'NO'),
  CountryOption(code: 'OM'),
  CountryOption(code: 'PK'),
  CountryOption(code: 'PW'),
  CountryOption(code: 'PS'),
  CountryOption(code: 'PA'),
  CountryOption(code: 'PG'),
  CountryOption(code: 'PY'),
  CountryOption(code: 'PE'),
  CountryOption(code: 'PH'),
  CountryOption(code: 'PN'),
  CountryOption(code: 'PL'),
  CountryOption(code: 'PT'),
  CountryOption(code: 'PR'),
  CountryOption(code: 'QA'),
  CountryOption(code: 'RO'),
  CountryOption(code: 'RU'),
  CountryOption(code: 'RW'),
  CountryOption(code: 'RE'),
  CountryOption(code: 'BL'),
  CountryOption(code: 'SH'),
  CountryOption(code: 'KN'),
  CountryOption(code: 'LC'),
  CountryOption(code: 'MF'),
  CountryOption(code: 'PM'),
  CountryOption(code: 'VC'),
  CountryOption(code: 'WS'),
  CountryOption(code: 'SM'),
  CountryOption(code: 'ST'),
  CountryOption(code: 'SA'),
  CountryOption(code: 'SN'),
  CountryOption(code: 'RS'),
  CountryOption(code: 'SC'),
  CountryOption(code: 'SL'),
  CountryOption(code: 'SG'),
  CountryOption(code: 'SX'),
  CountryOption(code: 'SK'),
  CountryOption(code: 'SI'),
  CountryOption(code: 'SB'),
  CountryOption(code: 'SO'),
  CountryOption(code: 'ZA'),
  CountryOption(code: 'GS'),
  CountryOption(code: 'SS'),
  CountryOption(code: 'ES'),
  CountryOption(code: 'LK'),
  CountryOption(code: 'SD'),
  CountryOption(code: 'SR'),
  CountryOption(code: 'SJ'),
  CountryOption(code: 'SE'),
  CountryOption(code: 'CH'),
  CountryOption(code: 'SY'),
  CountryOption(code: 'TW'),
  CountryOption(code: 'TJ'),
  CountryOption(code: 'TZ'),
  CountryOption(code: 'TH'),
  CountryOption(code: 'TL'),
  CountryOption(code: 'TG'),
  CountryOption(code: 'TK'),
  CountryOption(code: 'TO'),
  CountryOption(code: 'TT'),
  CountryOption(code: 'TN'),
  CountryOption(code: 'TM'),
  CountryOption(code: 'TC'),
  CountryOption(code: 'TV'),
  CountryOption(code: 'TR'),
  CountryOption(code: 'UG'),
  CountryOption(code: 'UA'),
  CountryOption(code: 'AE'),
  CountryOption(code: 'GB'),
  CountryOption(code: 'US'),
  CountryOption(code: 'UM'),
  CountryOption(code: 'UY'),
  CountryOption(code: 'UZ'),
  CountryOption(code: 'VU'),
  CountryOption(code: 'VE'),
  CountryOption(code: 'VN'),
  CountryOption(code: 'VG'),
  CountryOption(code: 'VI'),
  CountryOption(code: 'WF'),
  CountryOption(code: 'EH'),
  CountryOption(code: 'YE'),
  CountryOption(code: 'ZM'),
  CountryOption(code: 'ZW'),
  CountryOption(code: 'AX'),
];
