import 'rank_identity_models.dart';

/// Fully local player-facing fallback for the additive RP/profile layer.
///
/// This is intentionally presentation-only. It never writes RP, MMR, rewards,
/// matchmaking state or online-duel state. Screens can render immediately while
/// the rank backend is warming up, unavailable, or not deployed yet.
RankIdentityProfile buildRankIdentityFallback({
  String displayName = 'Sudoku Player',
  String username = 'player',
  String publicId = '',
}) {
  const rewardCoins = <String, int>{
    'bronze_3': 0,
    'bronze_2': 250,
    'bronze_1': 350,
    'silver_3': 600,
    'silver_2': 450,
    'silver_1': 550,
    'gold_3': 900,
    'gold_2': 650,
    'gold_1': 750,
    'platinum_3': 1200,
    'platinum_2': 850,
    'platinum_1': 950,
    'master_3': 1500,
    'master_2': 1200,
    'master_1': 1800,
  };

  final rewards = rankTierCatalog
      .map(
        (tier) => RankRewardState(
          rankKey: tier.key,
          rankName: tier.label,
          requiredPoints: tier.minPoints,
          amount: rewardCoins[tier.key] ?? 0,
          claimed: tier.key == 'bronze_3',
        ),
      )
      .toList(growable: false);

  const decorations = <RankDecoration>[
    RankDecoration(
      achievementId: 'undefeated_10',
      decorationKey: 'unbeaten_shield_10',
      rarity: 'rare',
      title: 'rank_decoration_undefeated_10_title',
      description: 'rank_decoration_undefeated_10_body',
      tier: 'silver',
      unlocked: false,
      selected: false,
    ),
    RankDecoration(
      achievementId: 'undefeated_25',
      decorationKey: 'unbeaten_shield_25',
      rarity: 'epic',
      title: 'rank_decoration_undefeated_25_title',
      description: 'rank_decoration_undefeated_25_body',
      tier: 'gold',
      unlocked: false,
      selected: false,
    ),
    RankDecoration(
      achievementId: 'undefeated_50',
      decorationKey: 'unbeaten_shield_50',
      rarity: 'legendary',
      title: 'rank_decoration_undefeated_50_title',
      description: 'rank_decoration_undefeated_50_body',
      tier: 'milestone',
      unlocked: false,
      selected: false,
    ),
    RankDecoration(
      achievementId: 'win_streak_5',
      decorationKey: 'streak_flame_5',
      rarity: 'common',
      title: 'rank_decoration_win_streak_5_title',
      description: 'rank_decoration_win_streak_5_body',
      tier: 'bronze',
      unlocked: false,
      selected: false,
    ),
    RankDecoration(
      achievementId: 'win_streak_10',
      decorationKey: 'streak_flame_10',
      rarity: 'epic',
      title: 'rank_decoration_win_streak_10_title',
      description: 'rank_decoration_win_streak_10_body',
      tier: 'gold',
      unlocked: false,
      selected: false,
    ),
    RankDecoration(
      achievementId: 'win_streak_25',
      decorationKey: 'streak_flame_25',
      rarity: 'legendary',
      title: 'rank_decoration_win_streak_25_title',
      description: 'rank_decoration_win_streak_25_body',
      tier: 'milestone',
      unlocked: false,
      selected: false,
    ),
    RankDecoration(
      achievementId: 'rank_silver',
      decorationKey: 'silver_crest',
      rarity: 'rare',
      title: 'rank_decoration_rank_silver_title',
      description: 'rank_decoration_rank_silver_body',
      tier: 'silver',
      unlocked: false,
      selected: false,
    ),
    RankDecoration(
      achievementId: 'rank_gold',
      decorationKey: 'gold_crest',
      rarity: 'epic',
      title: 'rank_decoration_rank_gold_title',
      description: 'rank_decoration_rank_gold_body',
      tier: 'gold',
      unlocked: false,
      selected: false,
    ),
    RankDecoration(
      achievementId: 'rank_platinum',
      decorationKey: 'platinum_crystal',
      rarity: 'epic',
      title: 'rank_decoration_rank_platinum_title',
      description: 'rank_decoration_rank_platinum_body',
      tier: 'platinum',
      unlocked: false,
      selected: false,
    ),
    RankDecoration(
      achievementId: 'rank_master',
      decorationKey: 'master_crown',
      rarity: 'legendary',
      title: 'rank_decoration_rank_master_title',
      description: 'rank_decoration_rank_master_body',
      tier: 'milestone',
      unlocked: false,
      selected: false,
    ),
    RankDecoration(
      achievementId: 'rank_master_i',
      decorationKey: 'master_i_crown',
      rarity: 'legendary',
      title: 'rank_decoration_rank_master_i_title',
      description: 'rank_decoration_rank_master_i_body',
      tier: 'milestone',
      unlocked: false,
      selected: false,
    ),
    RankDecoration(
      achievementId: 'giant_slayer',
      decorationKey: 'giant_slayer',
      rarity: 'epic',
      title: 'rank_decoration_giant_slayer_title',
      description: 'rank_decoration_giant_slayer_body',
      tier: 'gold',
      unlocked: false,
      selected: false,
    ),
    RankDecoration(
      achievementId: 'ranked_veteran_100',
      decorationKey: 'veteran_100',
      rarity: 'rare',
      title: 'rank_decoration_ranked_veteran_100_title',
      description: 'rank_decoration_ranked_veteran_100_body',
      tier: 'silver',
      unlocked: false,
      selected: false,
    ),
    RankDecoration(
      achievementId: 'ranked_veteran_500',
      decorationKey: 'veteran_500',
      rarity: 'epic',
      title: 'rank_decoration_ranked_veteran_500_title',
      description: 'rank_decoration_ranked_veteran_500_body',
      tier: 'platinum',
      unlocked: false,
      selected: false,
    ),
    RankDecoration(
      achievementId: 'ranked_veteran_1000',
      decorationKey: 'veteran_1000',
      rarity: 'legendary',
      title: 'rank_decoration_ranked_veteran_1000_title',
      description: 'rank_decoration_ranked_veteran_1000_body',
      tier: 'milestone',
      unlocked: false,
      selected: false,
    ),
    RankDecoration(
      achievementId: 'perfect_ranked_win',
      decorationKey: 'perfect_star',
      rarity: 'rare',
      title: 'rank_decoration_perfect_ranked_win_title',
      description: 'rank_decoration_perfect_ranked_win_body',
      tier: 'silver',
      unlocked: false,
      selected: false,
    ),
    RankDecoration(
      achievementId: 'perfect_ranked_wins_10',
      decorationKey: 'perfect_crystal_star',
      rarity: 'legendary',
      title: 'rank_decoration_perfect_ranked_wins_10_title',
      description: 'rank_decoration_perfect_ranked_wins_10_body',
      tier: 'platinum',
      unlocked: false,
      selected: false,
    ),
  ];

  final avatarKey = const RankIdentityKey(
    avatarKey: 'default',
    frameKey: 'bronze_3',
  ).encode();

  return RankIdentityProfile(
    publicId: publicId,
    username: username,
    displayName: displayName,
    avatarKey: avatarKey,
    selectedAvatarKey: 'default',
    selectedFrameKey: 'auto',
    effectiveFrameKey: 'bronze_3',
    selectedTitleKey: '',
    unlockedTitles: const <RankTitleOption>[],
    selectedDecorationAchievementIds: const <String>[],
    selectedDecorationKeys: const <String>[],
    rankPoints: 0,
    highestRankPoints: 0,
    rankKey: 'bronze_3',
    rankName: 'Bronze III',
    league: 'bronze',
    division: 3,
    nextRankKey: 'bronze_2',
    nextRankName: 'Bronze II',
    highestRankKey: 'bronze_3',
    highestRankName: 'Bronze III',
    pointsInDivision: 0,
    divisionSize: 300,
    pointsToNext: 300,
    progress: 0,
    unlockedFrameKeys: const <String>['bronze_3'],
    availableAvatarCount: 96,
    decorations: decorations,
    rankRewards: rewards,
    totalLifetimeRankReward: 12000,
    stats: const RankProgressionStats(
      rankedGames: 0,
      wins: 0,
      losses: 0,
      draws: 0,
      winStreak: 0,
      bestWinStreak: 0,
      undefeatedStreak: 0,
      bestUndefeatedStreak: 0,
      perfectWins: 0,
    ),
  );
}
