#!/usr/bin/env python3
"""Keep Android's default string resources complete for every translated key.

Android lint treats a string that exists only in values-<locale> as an
ExtraTranslation error because there is no guaranteed fallback for other
locales. Sudoku Duel keeps the canonical English copy in the iOS String Catalog
and exposes Android translations through native resources, so the two sources
must stay synchronized.

This script scans every localized Android values directory, finds translated
<string> names that are missing from the default values resources, resolves the
canonical English value from Localizable.xcstrings, and materializes only those
missing defaults into a generated resource file.

The generated file is deterministic and safe to commit. Existing hand-written
default resources always win: if a key is later added to another values/*.xml
file it is automatically removed from the generated fallback file on the next
run, preventing duplicate resources.
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path
from xml.etree import ElementTree as ET
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parents[1]
RES_DIR = ROOT / "android/app/src/main/res"
DEFAULT_VALUES_DIR = RES_DIR / "values"
GENERATED = DEFAULT_VALUES_DIR / "generated_translation_fallbacks.xml"
CATALOG = ROOT / "assets/localization/Localizable.xcstrings"


def _string_names(path: Path) -> set[str]:
    try:
        root = ET.parse(path).getroot()
    except ET.ParseError as exc:
        raise SystemExit(f"Invalid Android resource XML: {path}: {exc}") from exc

    return {
        element.attrib["name"]
        for element in root.findall("string")
        if element.attrib.get("name")
    }


def _is_locale_values_dir(path: Path) -> bool:
    """Return True only for Android resource directories carrying a locale."""
    if not path.is_dir() or not path.name.startswith("values-"):
        return False
    first_qualifier = path.name[len("values-") :].split("-", 1)[0]
    return bool(
        re.fullmatch(r"[a-z]{2,3}", first_qualifier)
        or first_qualifier.startswith("b+")
    )


def _translated_string_names() -> set[str]:
    names: set[str] = set()
    for values_dir in sorted(RES_DIR.glob("values-*")):
        if not _is_locale_values_dir(values_dir):
            continue
        for xml_path in sorted(values_dir.glob("*.xml")):
            names.update(_string_names(xml_path))
    return names


def _handwritten_default_names() -> set[str]:
    names: set[str] = set()
    for xml_path in sorted(DEFAULT_VALUES_DIR.glob("*.xml")):
        if xml_path == GENERATED:
            continue
        names.update(_string_names(xml_path))
    return names


def _english_catalog() -> dict[str, str]:
    catalog = json.loads(CATALOG.read_text(encoding="utf-8"))
    resolved: dict[str, str] = {}
    for key, definition in catalog.get("strings", {}).items():
        unit = (
            ((definition or {}).get("localizations") or {})
            .get("en", {})
            .get("stringUnit", {})
        )
        value = unit.get("value")
        if isinstance(value, str) and value:
            resolved[key] = value
    return resolved


def _android_value(value: str) -> str:
    # Android string resources require apostrophes to be escaped unless the
    # whole resource is quoted. Keep line breaks explicit and let Dart perform
    # the app's %1s/%1d placeholder interpolation after resources.getString().
    return (
        escape(value, {'"': "&quot;"})
        .replace("'", "\\'")
        .replace("\r\n", "\\n")
        .replace("\n", "\\n")
    )


def _render(missing: dict[str, str]) -> str:
    lines = [
        "<?xml version='1.0' encoding='utf-8'?>",
        "<!-- GENERATED by tool/sync_android_translation_fallbacks.py. -->",
        "<!-- Do not edit by hand; canonical English copy lives in Localizable.xcstrings. -->",
        "<resources>",
    ]
    for key in sorted(missing):
        value = missing[key]
        formatted = ' formatted="false"' if "%" in value else ""
        lines.append(
            f'    <string name="{key}"{formatted}>{_android_value(value)}</string>'
        )
    lines.append("</resources>")
    return "\n".join(lines) + "\n"


def sync() -> int:
    translated = _translated_string_names()
    defaults = _handwritten_default_names()
    missing_names = sorted(translated - defaults)
    english = _english_catalog()

    unresolved = [key for key in missing_names if key not in english]
    if unresolved:
        details = "\n".join(f"  - {key}" for key in unresolved)
        raise SystemExit(
            "Android translations contain keys with no canonical English "
            "fallback in Localizable.xcstrings:\n" + details
        )

    missing = {key: english[key] for key in missing_names}
    GENERATED.parent.mkdir(parents=True, exist_ok=True)
    rendered = _render(missing)
    previous = GENERATED.read_text(encoding="utf-8") if GENERATED.exists() else None
    if previous != rendered:
        GENERATED.write_text(rendered, encoding="utf-8")
        print(f"Updated {GENERATED.relative_to(ROOT)} with {len(missing)} fallbacks.")
    else:
        print(f"Android translation fallbacks already synchronized ({len(missing)} keys).")

    # Verify the final default namespace really covers every translated string.
    generated_names = _string_names(GENERATED)
    remaining = translated - defaults - generated_names
    unexpected = generated_names - set(missing_names)
    if remaining or unexpected:
        messages: list[str] = []
        if remaining:
            messages.append("Still missing: " + ", ".join(sorted(remaining)))
        if unexpected:
            messages.append("Unexpected generated keys: " + ", ".join(sorted(unexpected)))
        raise SystemExit("Android fallback verification failed: " + " | ".join(messages))

    print(
        f"Verified {len(translated)} translated Android string keys have a default fallback."
    )
    return len(missing)


def main() -> None:
    try:
        sync()
    except (OSError, json.JSONDecodeError) as exc:
        print(f"Android fallback synchronization failed: {exc}", file=sys.stderr)
        raise SystemExit(1) from exc


if __name__ == "__main__":
    main()
